def calculate(num1, num2, op):
    if op == '+':
        return num1 + num2
    elif op == '-':
        return num1 - num2
    elif op == '*':
        return num1 * num2
    elif op == '/':
        return num1 / num2 if num2 != 0 else "You silly goose. You can't divide by zero!"
    elif op == '=':
        return num1 == num2
    elif op == '>':
        return num1 > num2
    elif op == '<':
        return num1 < num2 
    elif op == '>=':
        return num1 >= num2
    elif op == '<=':
        return num1 <= num2
    elif op == '!=':
        return num1 != num2